version: '3.9'

services:

  scraper:
    build: .
    image: golang:latest
    container_name: crypto-scraper
    volumes:
      - ./src:/user/src/app
    #command: bash -c "go mod init webscraper"
    # command: bash -c "go get -u github.com/gin-gonic/gin"
    #command: bash -c "go get -u github.com/gocolly/colly/..."
