version: '3.9'

services:

  consumer-ada:
    build: .
    image: golang-kafka:consumer
    container_name: kafka-ada-consumer
    environment:
      TOPIC: ada-topic
      BROKER: kafka-broker1:9092
    ports:
      - 9090:8080
    volumes:
      - ./src:/user/src/app
    networks:
      - default
    # command: bash -c "go mod init kafka"
    # command: bash -c "go get github.com/gin-gonic/gin"
    # command: bash -c "go get github.com/joho/godotenv && go get github.com/segmentio/kafka-go"
    #command: bash -c "go get github.com/segmentio/kafka-go"

  consumer-btc:
    build: .
    image: golang-kafka:consumer
    container_name: kafka-btc-consumer
    environment:
      TOPIC: btc-topic
      BROKER: kafka-broker1:9092
    ports:
      - 9091:8080
    volumes:
      - ./src:/user/src/app
    networks:
      - default
    # command: bash -c "go mod init kafka"
    # command: bash -c "go get github.com/gin-gonic/gin"
    # command: bash -c "go get github.com/joho/godotenv && go get github.com/segmentio/kafka-go"
    #command: bash -c "go get github.com/segmentio/kafka-go"

networks:
  default:
    name: kafka_default
    external: true
